### ISSUE TITLE
授权拒绝后，再次授权，无法出现授权按钮

### ISSUE THREAD

**Issue by xiaojia21190** [ChenXianbin/egret_kit#6]

**Comment by xiaojia21190** [comment]
![image](https://user-images.githubusercontent.com/16084693/52772699-26fd8800-3074-11e9-99f3-4c32d1b08ded.png)
这代码再次调用不出现按钮

**Comment by TanYiBing** [comment]
> ![image](https://user-images.githubusercontent.com/16084693/52772699-26fd8800-3074-11e9-99f3-4c32d1b08ded.png)
> 这代码再次调用不出现按钮

需要清除授权数据的
